import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <h1 className="text-xl font-bold my-10">Go to app</h1>
        <Link href={"/app"}>
          <a className="my-8 py-2 px-4 rounded-md bg-orange-300">Open app</a>
        </Link>
      </main>
    </div>
  );
};

export default Home;
